### PR TITLE
More realistic WebRTC 1.0 timeline

### PR DESCRIPTION
**Pull request by aboba**
Related to Issue https://github.com/w3c/webrtc-charter/issues/21

### CODE REVIEW

**Review by stefhak — APPROVED** [review]
I think this is more realistic. But maybe W3M wants another "message" (i.e. "will soon be done") to the AC?

**Comment by aboba** [comment]
WebRTC has more underlying protocol functionality than every other W3C specification combined.  That implies a level of effort required for testing (e.g. WPT + KITE) that is greater than any other previous W3C specification. I'd prefer to be honest with W3M, rather than tell them what they may want to hear.

**Comment by dontcallmedom** [comment]
no question that we need an honest timeline, not a pleasant one :)

That said, for a timeline that extends until 2020, I know we will be asked a lot more details on our plans to get there and our approach to avoid further slippage, what we think is going to take so long, what could be done to accelerate the pace, etc.

I'll follow up by email when I'm back in my office

**Comment by dontcallmedom** [comment]
I've updated the pull request to use the timeline that @stefhak had suggested over email - @aboba can you confirm this is a workable one from your perspective?

**Comment by aboba** [comment]
@dontcallmedom Can we rebase this? I'm ok with it.

**Comment by stefhak** [comment]
LGTM.

**Pull request merged**
