### PR TITLE
Add description of WebRTC Object Oriented APIs

### PR DESCRIPTION
**Pull request by dontcallmedom**
As requested from W3C management review

### CODE REVIEW

**Review by vivienlacourba — APPROVED** [review]

**Comment by aboba** [comment]
I find this new text confusing. 

Some  functionality we have discussed (such as SVC encoder control) could be provided as a WebRTC 1.0 object extension without SDP support because no negotiation is required.  That's not really "less SDP dependent".  And on the other extreme there is functionality (such as allowing autonomous creation of IceTransport or DtlsTransport objects) that doesn't involve SDP at all, but probably can't be handled as a WebRTC 1.0 Extension, but rather as part of "WebRTC-NV".

**Review by aboba — CHANGES_REQUESTED** [review]
My understanding was that the object-oriented APIs were not restricted to things that would fit as WebRTC 1.0 extensions (such as an SDP-free API).  Overall, it seems like this change adds confusion, not clarity.

**Comment by stefhak** [comment]
I agree to @aboba - the way the PR talks about extensions to the current spec leads to the conclusion we could only work on stuff that fits on top of WebRTC 1.0, but that's not really the case.

**Comment by dontcallmedom** [comment]
thanks @aboba and @stefhak - can either or both of you suggest alternative wordings that are closer to what we think we should describe in the charter?

(the fact that I can't properly describe these APIs myself is reinforcing the need that we do so - both for the AC to properly understand the charter, and for the broader community to understand our directions)

**Comment by aboba** [comment]
The potential work on "WebRTC-NV" seems well enough described in the Charter. Potential work on additional data channel protocols for WebRTC 1.0 (or WebRTC-NV) seems to be covered by the description of potential data channel work, and the DSCP WebRTC 1.0 extension is also described.  So about the only thing not covered would be WebRTC 1.0 object extensions for SVC encoding. I'm not sure we can say there is consensus for that yet though, since although it has been discussed, there is no concrete proposal. But it would seem to be covered under the general "encode/decode" set of goals.

**Comment by stefhak** [comment]
Sorry @dontcallmedom :) I tend to agree to Bernard: Furhter down (after the list of "ongoing docs") I think WebRTC NV principles are outlined pretty well. I don't think we can say much more at the moment.

**Pull request closed without merging**
